/*Criando tabela reservas*/

CREATE TABLE RESERVA(
    COD_RES INT NOT NULL PRIMARY KEY,
    COD_HOSP INT NOT NULL REFERENCES HOSPEDE(COD_HOSP),
    COD_FUNC INT NOT NULL REFERENCES FUNCIONARIO(COD_FUNC),
    NUM INT NOT NULL REFERENCES APTO(NUM),
    DT_ENTRADA DATE NOT NULL,
    DT_SAI DATE NULL
);